### ISSUE TITLE
Question/"Request"

### ISSUE THREAD

**Issue by catomann** [hernejj/workspace-grid-cinnamon-applet#1]
Hey,

first off, thanks for making this! Cannot understand why this wasn't implemented from the getgo. However, as I'm switching between using only the keyboard and only the mouse, having to place my hand back on the keyboard to change workspace is counterproductive. (Ive mapped a mousebutton to expose, that is, emulating ctrl+alt+up to be able to change workspaces with the mouse)

Is it possible to also have the expose function aswell as this 'mod'?
regards,
Cato

**Comment by hernejj** [comment]
If your only concern is full mouse based operation, you can do it by clicking on the applet.  Clicking a workspace takes you to that workspace.  Clicking a line in the row indicator takes you to that row.

As far as using the keyboard to bring up the expo...There does not appear to be an easy way to do this at the moment.  My first thought was to define a keyboard shortcut but Cinnamon does not allow you to set a "switch-workspace-up" and ""switch-workspace-down" key binding.  Instead it repurposes them as "show-expo" and "show-scale".  So redefining the keyboard shortcut for "show expo" will really just redefine "switch-workspace-up".

The only workaround I can think of at the moment is If you have the expo applet in your panel, you can click on it to bring up the expo.  My applet could be made to NOT take over the "switch-workspace-up" (ctrl+alt+up) keybinding BUT then you would have no keyboard centric way to switch to the workspace above yours.  

Let me know if you have any ideas :).
Thanks for trying the applet. Please consider rating it on the Cinnamon website.

**Comment by catomann** [comment]
Thanks for the quick reply!

I did a little "dirty workaround" to enable showing the expo by adding a hot corner and binding the mousebutton to a script which in turn moves the mouse to the corner, clicks and moves the mouse back to the initial position.. Not the best solution, but it works well enough :)

If you figure out a more legit solution, Im all ears!

**Comment by catomann** [comment]
Ups. Missclicked close, but I guess the 'issue' should be closed anywho!

**Comment by hernejj** [comment]
There is now an option to leave the original keybindings for expo and scale as they are. This allows you to use expo and scale.
