### ISSUE TITLE
Inconsistent style with non-default theme

### ISSUE THREAD

**Issue by MrMitch** [hernejj/workspace-grid-cinnamon-applet#2]
The applet works fine, although it seems to conflict with the theme used in Cinnamon if it's not the default Cinnamon theme (I use [Tyr Jord](http://bimsebasse.deviantart.com/art/Tyr-347195334)).

When enabling the applet via the Cinnamon Settings panel, the thumbnails are bigger than my panel.

![Screenshot from 2013-03-08 15:58:55](https://f.cloud.github.com/assets/576772/236994/1bcbbffa-8806-11e2-8ad4-9d2e0d722acb.png)

I then tried to change the theme to the default Cinnamon theme, and it looks great with it. Changing back to my custom theme brings the applet to a normal size but the row selectors are gone (but the applet still works though).

![Screenshot from 2013-03-08 16:26:35](https://f.cloud.github.com/assets/576772/236995/1be67138-8806-11e2-936e-e37eee18b598.png)

Note that it also changes the theme for elements that are not linked to the applet, like the windows list (although I suspect it overrides some style for the whole panel):
**BEFORE ENABLING THE APPLET**
![Screenshot from 2013-03-08 16:50:21](https://f.cloud.github.com/assets/576772/237086/fafdd576-8808-11e2-8543-1ba71feb9cdb.png)

**AFTER ENABLING THE APPLET**
![Screenshot from 2013-03-08 16:56:03](https://f.cloud.github.com/assets/576772/237087/fb17ffe6-8808-11e2-97ea-00b5ebca4075.png)

Every reboot brings back the first situation where the thumbnails are too big and other elements of the theme are changed.
I tried to tweak the `stylesheet.css` file included with the applet but didn't get any positive results as it's not really my field of expertise.

**Comment by hernejj** [comment]
Thanks for the bug report :)  I'll look at these issues and try to fix them.

**Comment by MrMitch** [comment]
Thanks for your concern, this is a great applet that implements a behavior that I wish would be the default one in Cinnamon. Thanks a lot!

**Comment by hernejj** [comment]
MyMitch,
I think I've fixed the style and resizing issues with the applet.  If you have time, please try it out for me and let me know is anything is still wrong.  The latest code has already been uploaded to the Cinnamon Applets repository and can be found here:
http://cinnamon-spices.linuxmint.com/applets/view/116

**Comment by hernejj** [comment]
NOTE: If you switch themes you'll need to restart Cinnamon because Cinnamon throws out the applets custom CSS on a theme change.  if you do not, then the "row-indicator bars" will not draw.  This should sort itself out on a Cinnamon restart though.

**Comment by MrMitch** [comment]
Perfect! 
The problems mentionned in this issues are fixed. I found some other inconsistencies that i managed to fix by myself. Will do a pull request to let your be the juge of whether it should me merged or not.

**Comment by hernejj** [comment]
Request a pull for your changes, I'll take a look :).  Thanks again for contributing and please consider voting for this applet on the Cinnamon Applets page.

**Comment by MrMitch** [comment]
Of course! The applet totally deserves a 5 star rating ;)
See PR #4 for some fixes for a better integration with non-default themes
