### ISSUE TITLE
Use UP and DOWN arrows in expo mode to change row

### ISSUE THREAD

**Issue by MrMitch** [hernejj/workspace-grid-cinnamon-applet#6]
![](https://f.cloud.github.com/assets/576772/277650/d59f8f22-90cd-11e2-8acc-97d32330b272.png)

This is rather an idea for improvement than an issue in itself
In Expo mode, with a multi-row layout, when on the first line of workspaces, pushing the ↓ key should switch to the next row instead of the next workspace, and UP arrow should switch to the previous row.
Basically, up and down arrows should change rows.

**Comment by hernejj** [comment]
Good idea :)  I'll try to investigate for the next version.

**Comment by MrMitch** [comment]
This might help https://bitbucket.org/mathematicalcoffee/workspace-grid-gnome-shell-extension

**Comment by hernejj** [comment]
With Cinnamon 2.2, this works automatically now :)
