### ISSUE TITLE
Navigate between workspaces firstly in one row and then between rows with hmouse wheel (as it was in gnome 2)

### ISSUE THREAD

**Issue by horada** [hernejj/workspace-grid-cinnamon-applet#8]
Hi,
Big thanks for you effort on this applet!
It would be good to have possibility to change the default behavior when navigating between workspaces by using mouse wheel - firstly in one row and then between rows, and change it to firstly navigate in one column and than between columns (as it is in gnome2).
Thanks

**Comment by hernejj** [comment]
Thanks for your suggestion. I don't completely understand though. It should be easy to allow the mouse wheel to navigate up and down when the cursor is over the row indicator. Is this what you are suggesting? If not, can you provide some more detail?

**Comment by horada** [comment]
I'm sorry, my ability for explanation in English is quite limited.. I'll try to explain it on example:
If you have 2 rows and 4 columns:

```
1  2  3  4
5  6  7  8
```

the cycle would go this way: 1 5 2 6 3 7 4 8 .... or back...

**Comment by hernejj** [comment]
I see :). You want an option to either advance by column, or advance by row on wheel events.
This should be fairly simple. I'll see what I can do.

**Comment by horada** [comment]
I've tried to resolve this issue (I'm not JavaScript coder... I have just little knowledge about python and bash...). Firstly I wanted to solve it purely mathematically, but I didn't success, so I have to use few "if" statements :(... 
It's just replacement the switch logic... it will need some configuration variable to give user the ability to chose preferred direction...

```
diff --git a/workspace-grid@hernejj/GridStyle.js b/workspace-grid@hernejj/GridStyle.js
index b125b39..5a5426f 100644
--- a/workspace-grid@hernejj/GridStyle.js
+++ b/workspace-grid@hernejj/GridStyle.js
@@ -26,8 +26,18 @@ GridStyle.prototype = {
     onMouseScroll: function(actor, event){
         var idx = global.screen.get_active_workspace_index();

-        if (event.get_scroll_direction() == 0) idx--; 
-        else if (event.get_scroll_direction() == 1) idx++;
+        if (event.get_scroll_direction() == 0 && idx > 0) {
+          idx = idx - this.cols
+          if (idx < 0) {
+            idx = idx + (this.rows * this.cols -1);
+          }
+        }
+        else if (event.get_scroll_direction() == 1 && idx < (this.rows * this.cols) - 1) {
+          idx = idx + this.cols
+          if (idx >= (this.rows * this.cols)) {
+            idx = idx - (this.rows * this.cols -1);
+          }
+        }

         if(global.screen.get_workspace_by_index(idx) != null)
             global.screen.get_workspace_by_index(idx).activate(global.get_current_time());
```

Maybe it will help... maybe not and you will find clearer solution... I'm curious :)...

**Comment by hernejj** [comment]
This should be implemented in v0.7. Please let me know what you think.

**Comment by horada** [comment]
It behave quite oddly - with my configuration with 2 rows and 4 columns (described in 3th comment) - when scrolling down, it changes the workspaces in following order:
1, 5, 2, 6, 3, 5, 2, 6, 3, 5, 2, 6, 3, 5, 2, 6, ... ( ...2, 6, 3, 5,.. repeating)
And also back scrolling works quite oddly.. :)

**Comment by hernejj** [comment]
Yep, I can reproduce this. I'll look into it.

**Comment by hernejj** [comment]
Gah! Simple formula error :) It turns out that the problem only shows up when you have a different number of rows and columns. I use 3x3 so I did not see it in my testing.

v0.8 is up and should fix the problems :).

**Comment by horada** [comment]
Thanks! now it works perfectly...
(sorry for the delay...)
